//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EverShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int OrdId { get; set; }
        public int OrdUser { get; set; }
        public int OrdProduct { get; set; }
        public string OrdStatus { get; set; }
        public System.DateTime OrdCreatedAt { get; set; }
        public Nullable<System.DateTime> OrdUpdatedAt { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual User User { get; set; }
    }
}
